### ISSUE TITLE
How to retrieve route instance of flask-restx

### ISSUE THREAD

**Issue by delucca** [python-injector/flask_injector#79]
Hi :)

I've a project that uses both flask-injector, as well as flask-restx and I'm trying to figure out how to retrieve the actual controller instance I'm using on the app.

Considering this setup:
```
        flask_injector = FlaskInjector(
            app=app,
            modules=[RequestedManufacturerNameModule],
        )
```

If I try to run: `flask_injector.injector.get(<MyControllerClass>)` it returns a valid instance of that class, but that is not the instance that is being used by flask-restx.

Any thoughts?

**Comment by jstasiak** [comment]
Hey, with class-based views for every request handled a new instance is created as far as I remember so there's no "the instance", unfortunately. You'd have to do things a bit differently to reuse the same instance, I think.

May I ask what are you trying to do?
